### ISSUE TITLE
Errors running make commands

### ISSUE THREAD

**Issue by cdhawan66** [iconara/ec2pricing#10]
Hello,

I was trying to run your website locally. I am running it on ubuntu 16.04.2 LTS. 

**First issue**: While trying to do "make setup" it said it cant find the package.js file. So I had to create it myself and added your repo into the parameters. After doing this make setup ran successfully. But please let me know if I did not create the package correctly b/c this may be the start of the issue.

**Second Issue**: While trying to run the "make" command I get this error:

node_modules/uglify-js/bin/uglifyjs app/modules.js app/ec2pricing/filters.js app/ec2pricing/config.js app/ec2pricing/directives.js app/ec2pricing/controllers.js app/ec2pricing/utils.js \
	--source-map lib/app.js.map \
	--prefix relative \
	--beautify \
	--stats \
	--output lib/app.js
Supported options:
  content         null
  filename        null
  includeSources  false
  root            null
  url             null
ERROR: `lib/app.js.map` is not a supported option
    at DefaultsError.Object.defineProperty.get (eval at <anonymous> (/home/ubuntu/ec2pricing/public/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:79:23)
    at fatal (/home/ubuntu/ec2pricing/public/node_modules/uglify-js/bin/uglifyjs:268:52)
    at run (/home/ubuntu/ec2pricing/public/node_modules/uglify-js/bin/uglifyjs:225:9)
    at Object.<anonymous> (/home/ubuntu/ec2pricing/public/node_modules/uglify-js/bin/uglifyjs:155:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
Makefile:42: recipe for target 'lib/app.js' failed
make: *** [lib/app.js] Error 1

Looks like there is something wrong with one of the .js files? Please let me know if I am doing these steps correctly and what can be done to fix these errors. 

Thank you!

**Comment by iconara** [comment]
Not sure what's going on. `make setup` should run `npm install bower …` but it sounds from your description that it ran just `npm install`. There's no `package.json`, but there shouldn't have to be one.

Either way you might want to check out the `pricing-api-rewrite` branch, it's got the new version of the app, the one you're trying to run is old and will be replaced.

**Comment by iconara** [comment]
The new app is in the same repo, it's the `pricing-api-rewrite` branch.

**Comment by cdhawan66** [comment]
Okay thanks, are the steps for running the app the same as ec2pricing?

**Comment by iconara** [comment]
I think you need to run `make deps` to install dependencies and then `make dev` to start the compiler/server.
