### ISSUE TITLE
[Feature Request] Add filtering

### ISSUE THREAD

**Issue by luisdavim** [iconara/ec2pricing#11]
Hi, it would be nice to have a way to quickly find the instances that I'm looking for with a filter.
http://www.ec2instances.info/ has this but doesn't have the Calculator part that ec2pricing has.

**Comment by iconara** [comment]
Good idea, I'll leave this open until I have the time to implement it.

**Comment by excalq** [comment]
I have a use case this would be very helpful for. I often need to make server recommendations to those with the purse, and would like to filter the list (http://ec2pricing.net/beta/) to only include the instance types I'm comparing, keeping the column headings. This way I could have it all on one screen and screenshot it. Thanks!

**Comment by iconara** [comment]
I've rewritten and this issue unfortunately no longer applies.
