### ISSUE TITLE
0% progress in Firefox 49

### ISSUE THREAD

**Issue by iconara** [iconara/ec2pricing#5]
Firefox 49 doesn't get further than 0%, but it does seems like the data is loaded, so something in the wiring doesn't work.

**Comment by iconara** [comment]
Looks like it's the jsonp loading that breaks. Something with iframe security most likely.

**Comment by theznx** [comment]
Hello,
Just for raise this issue,
Same problem today with Firefox 51 (stable), Firefox 55.0a1 (actual Nightly) and with Firefox ESR (45.7.0)
Nothing appear in the JS console
Don't forget Firefox !! 
Have a nice day :)

**Comment by iconara** [comment]
Yeah, sorry about that. I wish there was a simple solution. I'm currently planning on rewriting the service to use AWS officially supported pricing "API" instead of using their private data. As you've probably seen if you've used another browser there are a few other glitches that have cropped up the last few months (like some instances reporting "undefined" x "undefined" in the disk column).

**Comment by iconara** [comment]
This is going to be solved by #8. You can start using it today at http://ec2pricing.net/beta
