### ISSUE TITLE
Button hiding unselected rows to easily see types similarity and difference

### ISSUE THREAD

**Issue by evgeny-goldin** [iconara/ec2pricing#9]
When comparing several instance types it helps to see only these specific instance types and not any other. What could help is being able to "hide" unselected rows. This way when several rows are selected and others are hidden by clicking a, say, "Hide Unselected" button - one is left with previously selected rows (types) only so it becomes easy to compare them. 

This way comparing, say, c3.2xlarge with c4.2xlarge and r3.2xlarge leaves one with only three rows without having to scroll up and down between the types. 

As a bonus I'd also highlight similar and different instance properties so it's clear what properties are identical among the selected types and what properties are different.

**Comment by iconara** [comment]
Good idea. I haven't had much time to work on this for a while, but I'll keep this open until I've got time to implement it.

**Comment by iconara** [comment]
I've rewritten and this issue unfortunately no longer applies.
